[package]
name = "ytsub"
version = "0.1.0"
edition = "2021"
description = "A subscriptions only TUI Youtube client that uses the Invidious API"
authors = ["Berke Enercan <berkeenercan@tutanota.com>"]
repository = "https://codeberg.org/sarowish/ytsub"
license = "GPL-3.0"
readme = "README.md"
keywords = ["youtube", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["derive"]}
crossterm = "0.22.1"
dirs = "4.0"
futures-util = "0.3"
num_cpus = "1.8"
rand = "0.8.4"
rusqlite = { version = "0.26.3", features = ["bundled"] }
webbrowser = "0.6"
nix = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.72"
tokio = { version = "1", features = ["time", "macros", "rt-multi-thread"] }
tui = { version = "0.16.0", default-features = false, features = ['crossterm'] }
ureq = { version = "2", features = ["json"] }
unicode-width = "0.1"
unicode-segmentation = "1.9"

[profile.release-lto]
inherits = "release"
lto = true
