[package]
name = "ytsub"
version = "0.3.1"
edition = "2021"
description = "A subscriptions only TUI Youtube client that uses the Invidious API"
authors = ["Berke Enercan <berkeenercan@tutanota.com>"]
repository = "https://github.com/sarowish/ytsub"
license = "GPL-3.0"
readme = "README.md"
keywords = ["youtube", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
clap = "4.0.15"
crossterm = "0.25.0"
dirs = "4.0.0"
futures-util = "0.3.24"
num_cpus = "1.13.1"
rand = "0.8.5"
rusqlite = "0.28.0"
webbrowser = "0.8.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
tokio = { version = "1.21.2", features = ["time", "macros", "rt-multi-thread"] }
tokio-util = "0.7.4"
tui = { version = "0.19.0", default-features = false, features = ['crossterm'] }
ureq = { version = "2.5.0", features = ["json"] }
unicode-width = "0.1.10"
unicode-segmentation = "1.10.0"
toml = "0.5.9"
lazy_static = "1.4.0"
csv = "1.1.6"
quick-xml = { version = "0.25.0", features = ["serialize"] }
chrono = "0.4.22"

[target.'cfg(unix)'.dependencies]
nix = "0.25.0"

[features]
bundled_sqlite = ["rusqlite/bundled"]

[profile.release-lto]
inherits = "release"
lto = true
