[package]
name = "ytsub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
rand = "0.8.4"
rusqlite = "0.26.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.72"
tui = { version = "0.16.0", default-features = false, features = ['crossterm'] }
ureq = { version = "2", features = ["json"] }
webbrowser = { git = "https://github.com/codota/webbrowser-rs", branch = "feature/add-suppress-output-flag-with-docs" }

[profile.release-lto]
inherits = "release"
lto = true
